/**
 * Property-based tests for validation utilities.
 * Feature: auth-navigation-flow
 *
 * Uses fast-check to verify correctness properties across many generated inputs.
 */

import * as fc from 'fast-check';
import {
  Email_Regex,
  validateCredential,
  validateEmail,
  validateName,
  validatePhone,
  sanitizeEmail,
  detectCredentialType,
} from '../validation';

// ─── Property 1: Invalid emails always produce an error ───────────────────────
// Validates: Requirements 4.3, 7.4

describe('Property 1: Invalid emails always produce an error', () => {
  it('returns a non-null error string for any non-empty string that fails Email_Regex', () => {
    fc.assert(
      fc.property(
        // Generate non-empty strings that do NOT match the email regex
        fc.string({ minLength: 1 }).filter((s) => !Email_Regex.test(s)),
        (value) => {
          const result = validateEmail(value);
          return result !== null && typeof result === 'string';
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ─── Property 2: Valid emails never produce an error ─────────────────────────
// Validates: Requirements 4.4, 7.5

describe('Property 2: Valid emails never produce an error', () => {
  it('returns null for any string generated by fc.emailAddress()', () => {
    fc.assert(
      fc.property(fc.emailAddress(), (value) => {
        return validateEmail(value) === null;
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 3: Email sanitize–validate round trip ──────────────────────────
// Validates: Requirements 7.6

describe('Property 3: Email sanitize–validate round trip', () => {
  it('validateEmail(sanitizeEmail(e).value) returns null for any valid email', () => {
    fc.assert(
      fc.property(fc.emailAddress(), (email) => {
        const { value } = sanitizeEmail(email);
        return validateEmail(value) === null;
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 4: Digit-leading inputs are detected as phone ──────────────────
// Validates: Requirements 5.2

describe('Property 4: Digit-leading inputs are detected as phone', () => {
  it('returns "phone" for any string whose first character is a digit', () => {
    fc.assert(
      fc.property(fc.stringMatching(/^\d.*/), (value) => {
        return detectCredentialType(value) === 'phone';
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 5: Letter-leading inputs are detected as email ─────────────────
// Validates: Requirements 5.3

describe('Property 5: Letter-leading inputs are detected as email', () => {
  it('returns "email" for any string whose first character is a letter (a-z or A-Z)', () => {
    fc.assert(
      fc.property(fc.stringMatching(/^[a-zA-Z].*/), (value) => {
        return detectCredentialType(value) === 'email';
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 7: Sign-up Continue button disabled unless all fields valid ─────
// Validates: Requirements 4.6

/**
 * Pure canSubmit logic extracted from SignUpScreen for direct testing.
 * Mirrors the implementation in SignUpScreen.tsx exactly.
 */
function canSubmitLogic(
  role: string | null,
  fullName: string,
  credential: string,
  email: string,
  phone: string,
  photoUri: string | null,
): boolean {
  if (!role || validateName(fullName)) return false;
  if (role === 'customer') {
    if (!credential.trim() || validateCredential(credential)) return false;
    return true;
  }
  if (!email.trim() || validateEmail(email)) return false;
  if (!phone.trim() || validatePhone(phone, { completeOnly: true })) return false;
  if (!photoUri) return false;
  return true;
}

describe('Property 7: Sign-up Continue button disabled unless all fields valid', () => {
  it('returns false when role is null regardless of other fields', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 2 }),
        fc.oneof(fc.emailAddress(), fc.stringMatching(/^\+614\d{8}$/)),
        (fullName, credential) => {
          return canSubmitLogic(null, fullName, credential, '', '', null) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when fullName is empty or whitespace-only', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('tradie', 'customer'),
        fc.stringMatching(/^\s*$/),
        fc.oneof(fc.emailAddress(), fc.stringMatching(/^\+614\d{8}$/)),
        (role, fullName, credential) => {
          return canSubmitLogic(role, fullName, credential, '', '', null) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when credential is empty or whitespace-only', () => {
    fc.assert(
      fc.property(
        fc.constant('customer'),
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc.stringMatching(/^\s*$/),
        (role, fullName, credential) => {
          return canSubmitLogic(role, fullName, credential, '', '', null) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when credential is invalid', () => {
    fc.assert(
      fc.property(
        fc.constant('customer'),
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc
          .string({ minLength: 1 })
          .filter(
            (s) =>
              s.trim().length > 0 &&
              validateCredential(s) !== null &&
              !s.trim().match(/^[\d+]/),
          ),
        (role, fullName, credential) => {
          return canSubmitLogic(role, fullName, credential, '', '', null) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when phone credential is incomplete', () => {
    fc.assert(
      fc.property(
        fc.constant('customer'),
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc.oneof(fc.constant(''), fc.constant('+61'), fc.stringMatching(/^\+61\d{1,7}$/)),
        (role, fullName, credential) => {
          return canSubmitLogic(role, fullName, credential, '', '', null) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when role is tradie and profile photo is missing', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc.emailAddress(),
        fc.stringMatching(/^\+614\d{8}$/),
        (fullName, email, phone) => {
          return canSubmitLogic('tradie', fullName, '', email, phone, null) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns true only when all fields are valid', () => {
    fc.assert(
      fc.property(
        fc.constant('customer'),
        fc.stringMatching(/^[A-Za-z][A-Za-z ]{1,}$/).filter((s) => s.trim().length >= 2),
        fc
          .oneof(fc.emailAddress(), fc.stringMatching(/^\+614\d{8}$/))
          .filter((credential) => validateCredential(credential) === null),
        (role, fullName, credential) => {
          return canSubmitLogic(role, fullName, credential, '', '', null) === true;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns true for tradie when email, phone, and photo are valid', () => {
    fc.assert(
      fc.property(
        fc.stringMatching(/^[A-Za-z][A-Za-z ]{1,}$/).filter((s) => s.trim().length >= 2),
        fc.emailAddress(),
        fc.stringMatching(/^\+614\d{8}$/),
        (fullName, email, phone) => {
          return canSubmitLogic('tradie', fullName, '', email, phone, 'file:///profile.jpg') === true;
        },
      ),
      { numRuns: 200 },
    );
  });
});
