/**
 * Property-based tests for validation utilities.
 * Feature: auth-navigation-flow
 *
 * Uses fast-check to verify correctness properties across many generated inputs.
 */

import * as fc from 'fast-check';
import {
  Email_Regex,
  validateEmail,
  sanitizeEmail,
  detectCredentialType,
} from '../validation';

// ─── Property 1: Invalid emails always produce an error ───────────────────────
// Validates: Requirements 4.3, 7.4

describe('Property 1: Invalid emails always produce an error', () => {
  it('returns a non-null error string for any non-empty string that fails Email_Regex', () => {
    fc.assert(
      fc.property(
        // Generate non-empty strings that do NOT match the email regex
        fc.string({ minLength: 1 }).filter((s) => !Email_Regex.test(s)),
        (value) => {
          const result = validateEmail(value);
          return result !== null && typeof result === 'string';
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ─── Property 2: Valid emails never produce an error ─────────────────────────
// Validates: Requirements 4.4, 7.5

describe('Property 2: Valid emails never produce an error', () => {
  it('returns null for any string generated by fc.emailAddress()', () => {
    fc.assert(
      fc.property(fc.emailAddress(), (value) => {
        return validateEmail(value) === null;
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 3: Email sanitize–validate round trip ──────────────────────────
// Validates: Requirements 7.6

describe('Property 3: Email sanitize–validate round trip', () => {
  it('validateEmail(sanitizeEmail(e).value) returns null for any valid email', () => {
    fc.assert(
      fc.property(fc.emailAddress(), (email) => {
        const { value } = sanitizeEmail(email);
        return validateEmail(value) === null;
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 4: Digit-leading inputs are detected as phone ──────────────────
// Validates: Requirements 5.2

describe('Property 4: Digit-leading inputs are detected as phone', () => {
  it('returns "phone" for any string whose first character is a digit', () => {
    fc.assert(
      fc.property(fc.stringMatching(/^\d.*/), (value) => {
        return detectCredentialType(value) === 'phone';
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 5: Letter-leading inputs are detected as email ─────────────────
// Validates: Requirements 5.3

describe('Property 5: Letter-leading inputs are detected as email', () => {
  it('returns "email" for any string whose first character is a letter (a-z or A-Z)', () => {
    fc.assert(
      fc.property(fc.stringMatching(/^[a-zA-Z].*/), (value) => {
        return detectCredentialType(value) === 'email';
      }),
      { numRuns: 200 },
    );
  });
});

// ─── Property 7: Sign-up Continue button disabled unless all fields valid ─────
// Validates: Requirements 4.6

import { validateName, validatePhone } from '../validation';

/**
 * Pure canSubmit logic extracted from SignUpScreen for direct testing.
 * Mirrors the implementation in SignUpScreen.tsx exactly.
 */
function canSubmitLogic(
  role: string | null,
  fullName: string,
  email: string,
  phone: string,
): boolean {
  if (!role) return false;
  if (!fullName.trim() || !email.trim() || !phone.trim()) return false;
  if (validateName(fullName) || validateEmail(email) || validatePhone(phone)) return false;
  return true;
}

describe('Property 7: Sign-up Continue button disabled unless all fields valid', () => {
  it('returns false when role is null regardless of other fields', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 2 }),
        fc.emailAddress(),
        fc.string({ minLength: 8 }).map((s) => s.replace(/\D/g, '0')),
        (fullName, email, phone) => {
          return canSubmitLogic(null, fullName, email, phone) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when fullName is empty or whitespace-only', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('tradie', 'customer'),
        fc.stringMatching(/^\s*$/), // empty or whitespace-only
        fc.emailAddress(),
        fc.string({ minLength: 8 }).map((s) => s.replace(/\D/g, '0')),
        (role, fullName, email, phone) => {
          return canSubmitLogic(role, fullName, email, phone) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when email is empty or whitespace-only', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('tradie', 'customer'),
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc.stringMatching(/^\s*$/), // empty or whitespace-only
        fc.string({ minLength: 8 }).map((s) => s.replace(/\D/g, '0')),
        (role, fullName, email, phone) => {
          return canSubmitLogic(role, fullName, email, phone) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when email is invalid (non-empty but fails Email_Regex)', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('tradie', 'customer'),
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc.string({ minLength: 1 }).filter((s) => !Email_Regex.test(s) && s.trim().length > 0),
        fc.string({ minLength: 8 }).map((s) => s.replace(/\D/g, '0')),
        (role, fullName, email, phone) => {
          return canSubmitLogic(role, fullName, email, phone) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns false when phone is empty or too short', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('tradie', 'customer'),
        fc.string({ minLength: 2 }).filter((s) => s.trim().length >= 2),
        fc.emailAddress(),
        fc.string({ maxLength: 7 }).map((s) => s.replace(/\D/g, '0')), // too short for validatePhone
        (role, fullName, email, phone) => {
          return canSubmitLogic(role, fullName, email, phone) === false;
        },
      ),
      { numRuns: 200 },
    );
  });

  it('returns true only when all fields are valid', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('tradie', 'customer'),
        // Valid name: at least 2 non-whitespace chars, only letters/spaces/hyphens/apostrophes
        fc.stringMatching(/^[A-Za-z][A-Za-z ]{1,}$/).filter((s) => s.trim().length >= 2),
        fc.emailAddress(),
        // Valid phone: at least 8 digits
        fc.string({ minLength: 8, maxLength: 15 }).map((s) => s.replace(/\D/g, '1')),
        (role, fullName, email, phone) => {
          return canSubmitLogic(role, fullName, email, phone) === true;
        },
      ),
      { numRuns: 200 },
    );
  });
});
