/**
 * Chat slice — state and synchronous reducers for the chat module.
 *
 * Responsibilities:
 *  - Owns the merged state of REST and Socket.IO transports for chat
 *    (conversations, messages, typing, presence, read receipts, connection
 *    status, send cooldown, in-app notifications, last socket error).
 *  - Provides synchronous reducers that thunks (Task 7.1, 7.2) and the
 *    socket-bound hook (Task 9.1) dispatch as side-effect-free state
 *    transitions.
 *  - Enforces the six message-list invariants from design Property 2 inside a
 *    single helper (`upsertMessage`) so every message-mutating reducer keeps
 *    them by construction:
 *      1. `ids.length === Object.keys(byId).length`.
 *      2. Every id in `ids` has a corresponding `byId` entry.
 *      3. `ids` is sorted ascending by `byId[id].createdAt`.
 *      4. Every server-confirmed `clientMessageId === k` is consistent with
 *         `clientMessageIdIndex[k]`.
 *      5. No two `byId` entries share the same `id`.
 *      6. No two `byId` entries share the same non-empty `clientMessageId`.
 *
 * Out of scope for this task:
 *  - Thunks (REST + socket transport selection) — see Task 7.1, 7.2.
 *  - Selectors — see Task 6.2.
 *  - Reducer registration in `src/store/index.ts` — see Task 6.3.
 */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit';
import { generateUuidV4 } from '../../api/chatHelpers';
import type { ConnectionStatus } from '../../api/chatSocket';
import type {
  ChatErrorCode,
  ChatOnlineStatusEvent,
  ChatReadEvent,
  ChatSocketError,
  ChatTypingEvent,
  ConversationListItem,
  CursorMeta,
  MessagePayload,
  MessageStatus,
  PaginatedMeta,
} from '../../api/chatTypes';

// ─── Public types ────────────────────────────────────────────────────────────

/** Local fetch/load status used across the slice's REST-driven scopes. */
export type ChatLoadStatus = 'idle' | 'loading' | 'succeeded' | 'failed';

/**
 * Error code attached to a {@link LocalMessage} when sending fails. Includes
 * the client-side `'CLIENT_VALIDATION'` sentinel for inputs that never reach
 * the server (matches the union used by `chatHelpers.prepareSend`).
 */
export type LocalMessageErrorCode = ChatErrorCode | 'CLIENT_VALIDATION';

/**
 * A {@link MessagePayload} extended with local-only metadata used to drive
 * the optimistic-send lifecycle. The base `status` field comes from the
 * server; `localStatus` is what the UI renders.
 */
export type LocalMessage = MessagePayload & {
  /** Local lifecycle override for optimistic / failed messages. */
  localStatus: MessageStatus;
  /** Populated when `localStatus === 'failed'`. */
  error?: { code: LocalMessageErrorCode; message: string };
};

/**
 * Per-conversation message bucket. The triple `(ids, byId, clientMessageIdIndex)`
 * is kept consistent by every reducer through {@link upsertMessage} —
 * see design Property 2.
 */
export type ConversationMessages = {
  /** Message ids ordered ascending by `byId[id].createdAt`. */
  ids: string[];
  byId: Record<string, LocalMessage>;
  /** Maps non-empty `clientMessageId` to the message id holding it. */
  clientMessageIdIndex: Record<string, string>;
  hasMore: boolean;
  nextBefore: string | null;
};

/** Latest typing-event timestamp recorded per (conversationId, userId). */
export type TypingEntry = {
  name: string;
  lastEventAt: number;
};

/** In-app banner notification surfaced by `chatSlice.notifications`. */
export type ChatNotification = {
  /** Local UUID v4 generated by the reducer. */
  id: string;
  title: string;
  body: string;
  conversationId?: string;
  receivedAt: number;
};

/** Per-conversation read-receipt tracking for the other participant. */
export type ConversationReadReceipt = {
  userId: string;
  lastReadMessageId: string | null;
  lastReadAt: string;
};

export type ChatSliceState = {
  // Connection
  connectionStatus: ConnectionStatus;
  socketError: { code: ChatErrorCode; message: string } | null;

  // Conversations (page-paginated)
  conversationIds: string[];
  conversationsById: Record<string, ConversationListItem>;
  conversationsMeta: PaginatedMeta | null;
  conversationsStatus: ChatLoadStatus;
  conversationsError: string | null;
  conversationsLoadingMore: boolean;
  /** Last applied search query (clamped, trimmed). Empty string = no search. */
  conversationsSearch: string;

  // Active conversation
  activeConversationId: string | null;

  // Messages (cursor-paginated, per conversation)
  messagesByConversation: Record<string, ConversationMessages>;
  messagesStatusByConversation: Record<string, ChatLoadStatus>;
  messagesLoadingOlder: Record<string, boolean>;

  // Typing — set of userIds currently typing per conversation.
  typingByConversation: Record<string, Record<string, TypingEntry>>;

  // Presence — userId → online flag.
  presence: Record<string, boolean>;

  // Read receipts (other participant) per conversation.
  readByConversation: Record<string, ConversationReadReceipt>;

  // Rate-limit cooldown.
  sendCooldownEndsAt: number | null;

  // In-app notifications surfaced by useChatNotifications.
  notifications: ChatNotification[];
};

const initialState: ChatSliceState = {
  connectionStatus: 'disconnected',
  socketError: null,

  conversationIds: [],
  conversationsById: {},
  conversationsMeta: null,
  conversationsStatus: 'idle',
  conversationsError: null,
  conversationsLoadingMore: false,
  conversationsSearch: '',

  activeConversationId: null,

  messagesByConversation: {},
  messagesStatusByConversation: {},
  messagesLoadingOlder: {},

  typingByConversation: {},
  presence: {},
  readByConversation: {},

  sendCooldownEndsAt: null,

  notifications: [],
};

// ─── Internal helpers (invariants, sorting) ──────────────────────────────────

/**
 * Comparator for the conversation list per design Property 1(c) and
 * Requirement 11.2. Orders descending by `lastMessageAt`, breaking ties by
 * descending `updatedAt`, then ascending `id`. Conversations with a missing
 * or empty `lastMessageAt` are positioned after all entries with one.
 */
function compareConversations(
  a: ConversationListItem,
  b: ConversationListItem,
): number {
  const aHas = typeof a.lastMessageAt === 'string' && a.lastMessageAt.length > 0;
  const bHas = typeof b.lastMessageAt === 'string' && b.lastMessageAt.length > 0;
  if (aHas && !bHas) return -1;
  if (!aHas && bHas) return 1;
  if (aHas && bHas) {
    if (a.lastMessageAt > b.lastMessageAt) return -1;
    if (a.lastMessageAt < b.lastMessageAt) return 1;
  }
  // Tie on lastMessageAt — fall through to updatedAt desc, then id asc.
  if (a.updatedAt > b.updatedAt) return -1;
  if (a.updatedAt < b.updatedAt) return 1;
  if (a.id < b.id) return -1;
  if (a.id > b.id) return 1;
  return 0;
}

/** Re-sorts `conversationIds` in-place using {@link compareConversations}. */
function sortConversationIds(state: ChatSliceState): void {
  state.conversationIds.sort((idA, idB) => {
    const a = state.conversationsById[idA];
    const b = state.conversationsById[idB];
    if (!a && !b) return 0;
    if (!a) return 1;
    if (!b) return -1;
    return compareConversations(a, b);
  });
}

/**
 * Re-sorts a conversation's `ids` ascending by `createdAt`, breaking ties
 * deterministically by `id` ascending so the order is stable across runs.
 */
function reorderMessages(c: ConversationMessages): void {
  c.ids.sort((idA, idB) => {
    const a = c.byId[idA];
    const b = c.byId[idB];
    if (a.createdAt < b.createdAt) return -1;
    if (a.createdAt > b.createdAt) return 1;
    if (idA < idB) return -1;
    if (idA > idB) return 1;
    return 0;
  });
}

/** Returns the existing conversation messages bucket or creates one. */
function ensureConversationMessages(
  state: ChatSliceState,
  conversationId: string,
): ConversationMessages {
  let c = state.messagesByConversation[conversationId];
  if (!c) {
    c = {
      ids: [],
      byId: {},
      clientMessageIdIndex: {},
      hasMore: false,
      nextBefore: null,
    };
    state.messagesByConversation[conversationId] = c;
  }
  return c;
}

/**
 * Inserts or replaces a message in a conversation bucket while preserving
 * every invariant from design Property 2.
 *
 * Resolution order:
 *  1. Match by `clientMessageId` (replaces an optimistic entry that may
 *     hold a temporary id, swapping it for the server-assigned one).
 *  2. Match by `id` (true duplicate — overwrite in place).
 *  3. Otherwise: insert as a new entry.
 *
 * After mutation, the message ids are re-sorted and the
 * `clientMessageIdIndex` is rebuilt for the affected entries.
 */
function upsertMessage(c: ConversationMessages, msg: LocalMessage): void {
  const cmid = msg.clientMessageId;
  let oldId: string | undefined;

  if (cmid && c.clientMessageIdIndex[cmid]) {
    oldId = c.clientMessageIdIndex[cmid];
  } else if (c.byId[msg.id]) {
    oldId = msg.id;
  }

  if (oldId !== undefined && oldId !== msg.id) {
    // Replacing an entry whose id is changing (optimistic temp id → real id).
    const prev = c.byId[oldId];
    delete c.byId[oldId];
    const idx = c.ids.indexOf(oldId);
    if (idx !== -1) c.ids.splice(idx, 1);
    if (
      prev &&
      typeof prev.clientMessageId === 'string' &&
      prev.clientMessageId.length > 0 &&
      prev.clientMessageId !== cmid &&
      c.clientMessageIdIndex[prev.clientMessageId] === oldId
    ) {
      delete c.clientMessageIdIndex[prev.clientMessageId];
    }
  }

  c.byId[msg.id] = msg;
  if (!c.ids.includes(msg.id)) c.ids.push(msg.id);
  if (typeof cmid === 'string' && cmid.length > 0) {
    c.clientMessageIdIndex[cmid] = msg.id;
  }
  reorderMessages(c);
}

/** Updates a conversation's `lastMessage` summary from a confirmed message. */
function updateConversationLastMessage(
  conv: ConversationListItem,
  message: MessagePayload,
): void {
  conv.lastMessage = {
    id: message.id,
    content: message.content,
    type: message.type,
    attachmentCount: message.attachments?.length ?? 0,
    senderId: message.sender.id,
    createdAt: message.createdAt,
  };
  conv.lastMessageAt = message.createdAt;
}

/**
 * Removes every trace of a conversation from auxiliary maps. Used by
 * `removeConversation` and `clearChatState` to keep the slice tidy.
 */
function clearConversationSideTables(
  state: ChatSliceState,
  conversationId: string,
): void {
  delete state.messagesByConversation[conversationId];
  delete state.messagesStatusByConversation[conversationId];
  delete state.messagesLoadingOlder[conversationId];
  delete state.typingByConversation[conversationId];
  delete state.readByConversation[conversationId];
}

// ─── Slice ───────────────────────────────────────────────────────────────────

const chatSlice = createSlice({
  name: 'chat',
  initialState,
  reducers: {
    // ── Connection ───────────────────────────────────────────────────────────

    /**
     * Updates {@link ChatSliceState.connectionStatus}. Also clears the
     * presence map when transitioning out of `'connected'` (Requirement
     * 14.5) so stale online indicators don't linger across a reconnect.
     */
    setConnectionStatus(state, action: PayloadAction<ConnectionStatus>) {
      const next = action.payload;
      const prev = state.connectionStatus;
      if (
        prev === 'connected' &&
        (next === 'reconnecting' || next === 'disconnected')
      ) {
        state.presence = {};
      }
      state.connectionStatus = next;
    },

    /** Records the most recent socket-level error for diagnostic display. */
    setSocketError(
      state,
      action: PayloadAction<ChatSocketError | null>,
    ) {
      const payload = action.payload;
      if (!payload || !payload.code) {
        state.socketError = null;
        return;
      }
      state.socketError = { code: payload.code, message: payload.message };
    },

    /**
     * Resets the slice to its initial state. Dispatched on logout and any
     * other moment we need a clean slate (Requirement 9.2, design Property 12).
     */
    clearChatState() {
      return {
        ...initialState,
        // Re-create nested objects so consumers don't share references with
        // the module-level constant.
        conversationIds: [],
        conversationsById: {},
        messagesByConversation: {},
        messagesStatusByConversation: {},
        messagesLoadingOlder: {},
        typingByConversation: {},
        presence: {},
        readByConversation: {},
        notifications: [],
      };
    },

    // ── Active conversation ──────────────────────────────────────────────────

    setActiveConversation(state, action: PayloadAction<string | null>) {
      state.activeConversationId = action.payload;
    },

    // ── Conversation list mutations ──────────────────────────────────────────

    /**
     * Inserts or updates a single conversation. Ignores payloads with a
     * missing or empty `id` so malformed `chat:conversation-updated` events
     * cannot corrupt the list (Requirement 11.4).
     */
    upsertConversation(state, action: PayloadAction<ConversationListItem>) {
      const conv = action.payload;
      if (!conv || typeof conv.id !== 'string' || conv.id.length === 0) {
        return;
      }
      state.conversationsById[conv.id] = conv;
      if (!state.conversationIds.includes(conv.id)) {
        state.conversationIds.push(conv.id);
      }
      sortConversationIds(state);
    },

    /**
     * Removes a conversation from the list and tears down all per-conversation
     * side tables. Used by the `CHAT_JOIN_FORBIDDEN` flow.
     */
    removeConversation(state, action: PayloadAction<string>) {
      const id = action.payload;
      if (typeof id !== 'string' || id.length === 0) return;
      if (state.conversationsById[id]) {
        delete state.conversationsById[id];
      }
      const idx = state.conversationIds.indexOf(id);
      if (idx !== -1) state.conversationIds.splice(idx, 1);
      clearConversationSideTables(state, id);
      if (state.activeConversationId === id) {
        state.activeConversationId = null;
      }
    },

    /**
     * Stores a paginated conversations response. When `replace` is true the
     * existing list is cleared first (typical for page 1); otherwise items
     * are merged dedup-by-id. Always re-sorts and updates meta.
     */
    mergeConversationsPage(
      state,
      action: PayloadAction<{
        items: ConversationListItem[];
        meta: PaginatedMeta;
        replace?: boolean;
      }>,
    ) {
      const { items, meta, replace } = action.payload;
      if (replace) {
        state.conversationIds = [];
        state.conversationsById = {};
      }
      for (const conv of items) {
        if (!conv || typeof conv.id !== 'string' || conv.id.length === 0) {
          continue;
        }
        state.conversationsById[conv.id] = conv;
        if (!state.conversationIds.includes(conv.id)) {
          state.conversationIds.push(conv.id);
        }
      }
      state.conversationsMeta = meta;
      state.conversationsStatus = 'succeeded';
      state.conversationsError = null;
      state.conversationsLoadingMore = false;
      sortConversationIds(state);
    },

    /**
     * Sets the load status for the page-paginated conversations list. The
     * `'loading'` transition clears any previous error so the screen can
     * render a fresh loading state without stale messaging; the `'failed'`
     * transition is owned by {@link setConversationsError} so that the
     * thunk can attach a human-readable message in one step.
     *
     * Used by `fetchConversationsThunk` to drive the pending state of
     * page-1 / search loads (Req 2.1, 3.1).
     */
    setConversationsStatus(state, action: PayloadAction<ChatLoadStatus>) {
      const next = action.payload;
      state.conversationsStatus = next;
      if (next === 'loading' || next === 'succeeded') {
        state.conversationsError = null;
      }
    },

    /**
     * Records a paginated-list error and transitions the status to
     * `'failed'`. Passing `null` clears the error without changing the
     * status (useful when a follow-up retry succeeds and a fresh
     * `mergeConversationsPage` is about to run).
     *
     * Used by `fetchConversationsThunk` (Req 2.6).
     */
    setConversationsError(state, action: PayloadAction<string | null>) {
      const message = action.payload;
      state.conversationsError = message;
      if (message != null) {
        state.conversationsStatus = 'failed';
        // A failed load also implies any in-flight pagination has ended.
        state.conversationsLoadingMore = false;
      }
    },

    /**
     * Sets the in-flight flag for paginated conversation loads. The
     * `fetchConversationsThunk` flips this to `true` immediately before
     * issuing a `page > 1` request and back to `false` on success
     * (via {@link mergeConversationsPage}) or failure (Req 4.3 — at most
     * one in-flight pagination per scope).
     */
    setConversationsLoadingMore(state, action: PayloadAction<boolean>) {
      state.conversationsLoadingMore = Boolean(action.payload);
    },

    /**
     * Updates only the `unreadCount` of an existing conversation without
     * touching `lastMessage` / `lastMessageAt`. The list ordering is
     * unchanged because conversations sort by `lastMessageAt` — unread
     * mutations don't promote rows. No-ops for unknown ids.
     *
     * Used by `markConversationReadThunk` (Req 13.3, 13.4, 13.6, 16.2).
     */
    setConversationUnreadCount(
      state,
      action: PayloadAction<{ conversationId: string; unreadCount: number }>,
    ) {
      const { conversationId, unreadCount } = action.payload;
      const conv = state.conversationsById[conversationId];
      if (!conv) return;
      if (typeof unreadCount !== 'number' || !Number.isFinite(unreadCount)) {
        return;
      }
      conv.unreadCount = Math.max(0, unreadCount);
    },

    /**
     * Replaces the conversation list with the search results and records the
     * applied query. Mirrors `mergeConversationsPage` with `replace: true`
     * but preserves the search context for the screen layer.
     */
    applyConversationSearchResults(
      state,
      action: PayloadAction<{
        items: ConversationListItem[];
        meta: PaginatedMeta;
        search: string;
      }>,
    ) {
      const { items, meta, search } = action.payload;
      state.conversationIds = [];
      state.conversationsById = {};
      for (const conv of items) {
        if (!conv || typeof conv.id !== 'string' || conv.id.length === 0) {
          continue;
        }
        state.conversationsById[conv.id] = conv;
        if (!state.conversationIds.includes(conv.id)) {
          state.conversationIds.push(conv.id);
        }
      }
      state.conversationsMeta = meta;
      state.conversationsStatus = 'succeeded';
      state.conversationsError = null;
      state.conversationsLoadingMore = false;
      state.conversationsSearch = typeof search === 'string' ? search : '';
      sortConversationIds(state);
    },

    // ── Message mutations ────────────────────────────────────────────────────

    /**
     * Inserts a locally-generated optimistic message into the conversation.
     * The caller is expected to set `localStatus: 'pending'` and provide a
     * stable `clientMessageId` so a subsequent ack/echo can locate the entry.
     */
    insertOptimisticMessage(
      state,
      action: PayloadAction<{
        conversationId: string;
        message: LocalMessage;
      }>,
    ) {
      const { conversationId, message } = action.payload;
      if (
        !conversationId ||
        !message ||
        typeof message.id !== 'string' ||
        message.id.length === 0
      ) {
        return;
      }
      const c = ensureConversationMessages(state, conversationId);
      upsertMessage(c, message);
    },

    /**
     * Replaces an optimistic message with the server payload using
     * `clientMessageId` as the join key (design Property 2(d)). When no
     * matching optimistic exists, the server payload is still inserted —
     * this keeps the reducer idempotent under retransmission.
     */
    replaceOptimisticMessage(
      state,
      action: PayloadAction<{
        conversationId: string;
        clientMessageId: string;
        message: MessagePayload;
      }>,
    ) {
      const { conversationId, clientMessageId, message } = action.payload;
      if (!conversationId || !message) return;
      const c = ensureConversationMessages(state, conversationId);
      const local: LocalMessage = {
        ...message,
        clientMessageId: message.clientMessageId ?? clientMessageId,
        localStatus: 'sent',
      };
      upsertMessage(c, local);
    },

    /**
     * Marks an optimistic message as failed. No-ops when the
     * `clientMessageId` is unknown so callers can dispatch unconditionally
     * from error handlers.
     */
    markMessageFailed(
      state,
      action: PayloadAction<{
        conversationId: string;
        clientMessageId: string;
        error: { code: LocalMessageErrorCode; message: string };
      }>,
    ) {
      const { conversationId, clientMessageId, error } = action.payload;
      const c = state.messagesByConversation[conversationId];
      if (!c) return;
      const id = c.clientMessageIdIndex[clientMessageId];
      if (!id) return;
      const msg = c.byId[id];
      if (!msg) return;
      msg.localStatus = 'failed';
      msg.error = { code: error.code, message: error.message };
    },

    /**
     * Applies an inbound `chat:message` payload. Handles dedup-by-id and
     * dedup-by-`clientMessageId`, updates the conversation's `lastMessage` /
     * `lastMessageAt`, increments `unreadCount` only when the message
     * belongs to a non-active conversation and is from another user
     * (Requirement 10.4), and re-sorts the conversation list.
     */
    applyServerMessage(
      state,
      action: PayloadAction<{
        message: MessagePayload;
        activeConversationId: string | null;
        selfUserId: string | null;
      }>,
    ) {
      const { message, activeConversationId, selfUserId } = action.payload;
      if (!message || typeof message.conversationId !== 'string') return;
      const conversationId = message.conversationId;

      // Detect duplicates (id or clientMessageId match) so we don't bump
      // unread count on a re-emitted echo.
      const c = ensureConversationMessages(state, conversationId);
      const wasKnownById = Boolean(c.byId[message.id]);
      const wasKnownByCmid =
        typeof message.clientMessageId === 'string' &&
        message.clientMessageId.length > 0 &&
        Boolean(c.clientMessageIdIndex[message.clientMessageId]);
      const isFreshInsert = !wasKnownById && !wasKnownByCmid;

      const local: LocalMessage = { ...message, localStatus: 'sent' };
      upsertMessage(c, local);

      const conv = state.conversationsById[conversationId];
      if (conv) {
        updateConversationLastMessage(conv, message);
        if (
          isFreshInsert &&
          conversationId !== activeConversationId &&
          message.sender.id !== selfUserId
        ) {
          conv.unreadCount = (conv.unreadCount ?? 0) + 1;
        }
        sortConversationIds(state);
      }
    },

    /**
     * Prepends a cursor page of historical messages and records the new
     * `hasMore` / `nextBefore` cursor metadata.
     */
    prependCursorPage(
      state,
      action: PayloadAction<{
        conversationId: string;
        items: MessagePayload[];
        meta: CursorMeta;
      }>,
    ) {
      const { conversationId, items, meta } = action.payload;
      if (!conversationId) return;
      const c = ensureConversationMessages(state, conversationId);
      for (const m of items) {
        if (!m || typeof m.id !== 'string' || m.id.length === 0) continue;
        upsertMessage(c, { ...m, localStatus: 'sent' });
      }
      c.hasMore = Boolean(meta?.hasMore);
      c.nextBefore = meta?.nextBefore ?? null;
    },

    /**
     * Replaces the message bucket for a conversation with a fresh page of
     * server-supplied messages and records the cursor metadata. Used by
     * `fetchMessagesThunk` for the initial load — it discards any prior
     * server-confirmed messages so a re-mount of `ChatDetailScreen` always
     * matches the server's view.
     *
     * Pending / failed local messages are deliberately preserved so that an
     * optimistic send issued during the initial fetch is not blown away
     * when the response lands. The server-supplied items are upserted
     * after the bucket is reset; if any of them collide with a preserved
     * pending message via `clientMessageId`, the existing dedup logic in
     * {@link upsertMessage} handles the swap correctly.
     *
     * Used by `fetchMessagesThunk` (Req 5.1, 5.2).
     */
    setMessagesPage(
      state,
      action: PayloadAction<{
        conversationId: string;
        items: MessagePayload[];
        meta: CursorMeta;
      }>,
    ) {
      const { conversationId, items, meta } = action.payload;
      if (!conversationId) return;
      const existing = state.messagesByConversation[conversationId];

      // Carry over pending / failed local messages so an in-flight
      // optimistic send is not lost when the initial fetch resolves.
      const preserved: LocalMessage[] = [];
      if (existing) {
        for (const id of existing.ids) {
          const m = existing.byId[id];
          if (m && (m.localStatus === 'pending' || m.localStatus === 'failed')) {
            preserved.push(m);
          }
        }
      }

      const c: ConversationMessages = {
        ids: [],
        byId: {},
        clientMessageIdIndex: {},
        hasMore: Boolean(meta?.hasMore),
        nextBefore: meta?.nextBefore ?? null,
      };
      state.messagesByConversation[conversationId] = c;

      for (const m of items) {
        if (!m || typeof m.id !== 'string' || m.id.length === 0) continue;
        upsertMessage(c, { ...m, localStatus: 'sent' });
      }
      // Re-insert preserved pending / failed entries; upsertMessage handles
      // the case where the server happens to have echoed one already.
      for (const m of preserved) {
        upsertMessage(c, m);
      }
    },

    /**
     * Tracks the per-conversation initial-fetch status for messages. Used
     * by `fetchMessagesThunk` to drive the initial loading / failed
     * states surfaced by `ChatDetailScreen`.
     */
    setMessagesStatus(
      state,
      action: PayloadAction<{
        conversationId: string;
        status: ChatLoadStatus;
      }>,
    ) {
      const { conversationId, status } = action.payload;
      if (!conversationId) return;
      state.messagesStatusByConversation[conversationId] = status;
    },

    /**
     * Tracks the per-conversation in-flight flag for older-page (cursor)
     * fetches. The `fetchOlderMessagesThunk` reads this flag (along with
     * `messagesByConversation[id].hasMore`) to enforce the at-most-one
     * in-flight pagination guard from Req 5.5.
     */
    setMessagesLoadingOlder(
      state,
      action: PayloadAction<{ conversationId: string; loading: boolean }>,
    ) {
      const { conversationId, loading } = action.payload;
      if (!conversationId) return;
      state.messagesLoadingOlder[conversationId] = Boolean(loading);
    },

    // ── Typing ──────────────────────────────────────────────────────────────

    /** Records an inbound `chat:typing` event with the receive timestamp. */
    setTyping(state, action: PayloadAction<ChatTypingEvent>) {
      const { conversationId, userId, name } = action.payload;
      if (typeof conversationId !== 'string' || conversationId.length === 0) {
        return;
      }
      if (typeof userId !== 'string' || userId.length === 0) return;
      let map = state.typingByConversation[conversationId];
      if (!map) {
        map = {};
        state.typingByConversation[conversationId] = map;
      }
      map[userId] = {
        name: typeof name === 'string' ? name : '',
        lastEventAt: Date.now(),
      };
    },

    /** Removes the typing entry for a given (conversationId, userId). */
    clearTyping(state, action: PayloadAction<ChatTypingEvent>) {
      const { conversationId, userId } = action.payload;
      const map = state.typingByConversation[conversationId];
      if (!map) return;
      if (map[userId]) delete map[userId];
      if (Object.keys(map).length === 0) {
        delete state.typingByConversation[conversationId];
      }
    },

    // ── Read receipts ───────────────────────────────────────────────────────

    setReadReceipt(state, action: PayloadAction<ChatReadEvent>) {
      const { conversationId, userId, lastReadMessageId, lastReadAt } =
        action.payload;
      if (typeof conversationId !== 'string' || conversationId.length === 0) {
        return;
      }
      state.readByConversation[conversationId] = {
        userId,
        lastReadMessageId,
        lastReadAt,
      };
    },

    // ── Presence ────────────────────────────────────────────────────────────

    /**
     * Records the online flag for a user. Ignores malformed payloads per
     * Requirement 14.4.
     */
    setPresence(state, action: PayloadAction<ChatOnlineStatusEvent>) {
      const { userId, isOnline } = action.payload;
      if (typeof userId !== 'string' || userId.length === 0) return;
      if (typeof isOnline !== 'boolean') return;
      state.presence[userId] = isOnline;
    },

    // ── Notifications ───────────────────────────────────────────────────────

    pushNotification(
      state,
      action: PayloadAction<{
        title: string;
        body: string;
        conversationId?: string;
      }>,
    ) {
      const { title, body, conversationId } = action.payload;
      const entry: ChatNotification = {
        id: generateUuidV4(),
        title: typeof title === 'string' ? title : '',
        body: typeof body === 'string' ? body : '',
        receivedAt: Date.now(),
      };
      if (typeof conversationId === 'string' && conversationId.length > 0) {
        entry.conversationId = conversationId;
      }
      state.notifications.push(entry);
    },

    dismissNotification(state, action: PayloadAction<string>) {
      const id = action.payload;
      const idx = state.notifications.findIndex((n) => n.id === id);
      if (idx !== -1) state.notifications.splice(idx, 1);
    },

    // ── Send cooldown ───────────────────────────────────────────────────────

    /**
     * Sets the rate-limit cooldown deadline (epoch ms). Newer or later
     * deadlines win so a fresh 429 always extends the cooldown.
     */
    setSendCooldown(state, action: PayloadAction<{ endsAt: number }>) {
      const { endsAt } = action.payload;
      if (typeof endsAt !== 'number' || !Number.isFinite(endsAt)) return;
      if (state.sendCooldownEndsAt == null || endsAt > state.sendCooldownEndsAt) {
        state.sendCooldownEndsAt = endsAt;
      }
    },

    clearSendCooldown(state) {
      state.sendCooldownEndsAt = null;
    },
  },
});

export const {
  setConnectionStatus,
  setSocketError,
  clearChatState,
  setActiveConversation,
  upsertConversation,
  removeConversation,
  mergeConversationsPage,
  applyConversationSearchResults,
  setConversationsStatus,
  setConversationsError,
  setConversationsLoadingMore,
  setConversationUnreadCount,
  insertOptimisticMessage,
  replaceOptimisticMessage,
  markMessageFailed,
  applyServerMessage,
  prependCursorPage,
  setMessagesPage,
  setMessagesStatus,
  setMessagesLoadingOlder,
  setTyping,
  clearTyping,
  setReadReceipt,
  setPresence,
  pushNotification,
  dismissNotification,
  setSendCooldown,
  clearSendCooldown,
} = chatSlice.actions;

export default chatSlice.reducer;
